apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tf-xsubnets.gcp.demo.upbound.io
  labels:
    provider: gcp
    implementation: terraform
spec:
  compositeTypeRef:
    apiVersion: gcp.demo.upbound.io/v1alpha1
    kind: XSubnet
  resources:
    - name: tf-vpc-and-subnet
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          forProvider:
            source: Inline
            module: |
              variable "vpcName" { }

              resource "google_compute_network" "custom-test" {
                name                    = var.vpcName
                auto_create_subnetworks = false
              }
              resource "google_compute_subnetwork" "custom-subnet" {
                name          = "demo-tf-subnetwork"
                ip_cidr_range = "10.2.0.0/16"
                region        = "us-central1"
              network       = google_compute_network.custom-test.id
              }
            vars:
              - key: vpcName
      patches:
        - fromFieldPath: spec.vpcName
          toFieldPath: spec.forProvider.vars[0].value
        