apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xorgpolicy.gcp.demo.upbound.io
spec:
  group: gcp.demo.upbound.io
  names:
    kind: XOrgpolicy
    plural: xorgpolicy
  claimNames:
    kind: orgid
    plural: orgid
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              orgid:
                type: string
            required:
            - orgid
          status:
            description: A Status represents the observed state
            properties:
              share:
                description: Freeform field containing status information
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object