apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgke.gke-demo-api.example.org
spec:
  group: gke-demo-api.example.org
  names:
    kind: XGke
    plural: xgke
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              initialNodeCount:
                type: integer
                default: 1
              location:
                type: string
                default: "US"
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^US$'
            required:
              - location
              - initialNodeCount
  claimNames:
    kind: Gke
    plural: gke