apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgce.gce-api.example.org
spec:
  group: gce-api.example.org
  names:
    kind: XGce
    plural: xgce
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              zone:
                type: string
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^US$'
            required:
              - zone
  claimNames:
    kind: Gce
    plural: gce
      